In [1]:
from casacore.tables import table, tablecopy, tablerename, tabledelete, taql
from pathlib import Path
import shutil
import numpy as np
import matplotlib.pyplot as plt
from fixms.fix_ms_corrs import get_pol_axis_coro

/scratch3/tho822/miniforge3/envs/flint/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
in_path = Path("/scratch3/tho822/flint_oh/70731_bak")
ms_list = sorted(list(in_path.glob("*.ms")))
out_dir = Path("/scratch3/tho822/flint_oh/70731")

In [3]:
for ms in ms_list:
    print(ms)
    new_ms = out_dir / ms.name
    if new_ms.exists():
        shutil.rmtree(new_ms)
    shutil.copytree(ms, new_ms)

    feed_path = new_ms / "FEED"


    with table(str(feed_path), readonly=False) as feed:
        RECEPTOR_ANGLE = feed.getcol("RECEPTOR_ANGLE")
        nrows = feed.nrows()
        row_idxs = np.arange(nrows)
        selected = (RECEPTOR_ANGLE == RECEPTOR_ANGLE[0]).sum(axis=1).astype(bool)
        feed.removerows(row_idxs[~selected])
        

/scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam00_averaged_cal.leakage.ms
Successful read/write open of default-locked table /scratch3/tho822/flint_oh/70731/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam00_averaged_cal.leakage.ms/FEED: 12 columns, 31104 rows
/scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam01_averaged_cal.leakage.ms
Successful read/write open of default-locked table /scratch3/tho822/flint_oh/70731/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam01_averaged_cal.leakage.ms/FEED: 12 columns, 31104 rows
/scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam02_averaged_cal.leakage.ms
Successful read/write open of default-locked table /scratch3/tho822/flint_oh/70731/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam02_averaged_cal.leakage.ms/FEED: 12 columns, 31104 rows
/scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_

In [20]:
main = table(str(ms), readonly=True)
feed = table(str(ms /"FEED"), readonly=True)
feed_fix = table(str(feed_path), readonly=False)
main

Successful readonly open of default-locked table /scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam35_averaged_cal.leakage.ms: 23 columns, 492840 rows
Successful readonly open of default-locked table /scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam35_averaged_cal.leakage.ms/FEED: 12 columns, 31104 rows
Successful read/write open of default-locked table /scratch3/tho822/flint_oh/70731/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam35_averaged_cal.leakage.ms/FEED: 12 columns, 10368 rows


In [30]:
field = table(str(ms / "FIELD"), readonly=True)

Successful readonly open of default-locked table /scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam35_averaged_cal.leakage.ms/FIELD: 9 columns, 3 rows


In [32]:
main

In [47]:
feed

In [46]:
feed.getcol("ANTENNA_ID")

array([ 0,  0,  0, ..., 35, 35, 35], dtype=int32)

In [43]:
with table(str(ms / "FEED")) as tab:
    thing = taql("SELECT * FROM $tab WHERE FEED_ID == 35")
thing.getcol("RECEPTOR_ANGLE")

Successful readonly open of default-locked table /scratch3/tho822/flint_oh/70731_bak/scienceData.G334_1666_A_1.SB70731.G334_1666_A_1.beam35_averaged_cal.leakage.ms/FEED: 12 columns, 31104 rows


array([[2.36883067, 3.939627  ],
       [2.36883067, 3.939627  ],
       [2.36883067, 3.939627  ],
       ...,
       [2.37779469, 3.94859101],
       [2.37779469, 3.94859101],
       [2.37779469, 3.94859101]])

In [25]:
(main.getcol("FEED1") == 35).all()

np.True_

In [26]:
(main.getcol("FEED2") == 35).all()

np.True_

In [29]:
feed_fix.getcol("FEED_ID")

array([ 0,  1,  2, ..., 33, 34, 35], dtype=int32)

In [17]:
np.unique(main.FEED1)

KeyboardInterrupt: 

In [13]:
np.unique(feed.TIME)

array([5.24592431e+09, 5.24592524e+09, 5.24592616e+09, 5.24592708e+09,
       5.24592799e+09, 5.24592891e+09, 5.24592983e+09, 5.24593075e+09,
       5.24593168e+09, 5.24593260e+09, 5.24593352e+09, 5.24593443e+09,
       5.24593535e+09, 5.24593627e+09, 5.24593719e+09, 5.24593811e+09,
       5.24593904e+09, 5.24593996e+09, 5.24594087e+09, 5.24594179e+09,
       5.24594271e+09, 5.24594363e+09, 5.24594455e+09, 5.24603141e+09])

In [14]:
np.unique(main.TIME)

array([5.24592386e+09, 5.24592387e+09, 5.24592388e+09, 5.24592389e+09,
       5.24592390e+09, 5.24592391e+09, 5.24592392e+09, 5.24592393e+09,
       5.24592394e+09, 5.24592395e+09, 5.24592396e+09, 5.24592397e+09,
       5.24592398e+09, 5.24592399e+09, 5.24592400e+09, 5.24592401e+09,
       5.24592402e+09, 5.24592403e+09, 5.24592404e+09, 5.24592405e+09,
       5.24592406e+09, 5.24592407e+09, 5.24592408e+09, 5.24592409e+09,
       5.24592410e+09, 5.24592411e+09, 5.24592412e+09, 5.24592413e+09,
       5.24592414e+09, 5.24592415e+09, 5.24592416e+09, 5.24592417e+09,
       5.24592418e+09, 5.24592419e+09, 5.24592420e+09, 5.24592421e+09,
       5.24592422e+09, 5.24592423e+09, 5.24592424e+09, 5.24592424e+09,
       5.24592425e+09, 5.24592426e+09, 5.24592427e+09, 5.24592428e+09,
       5.24592429e+09, 5.24592430e+09, 5.24592431e+09, 5.24592432e+09,
       5.24592433e+09, 5.24592434e+09, 5.24592435e+09, 5.24592436e+09,
       5.24592437e+09, 5.24592438e+09, 5.24592439e+09, 5.24592440e+09,
      

In [ ]:
await get_pol_axis_coro(new_ms)

<Quantity -90.724 deg>